//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Frooty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_about
    {
        public int id_About { get; set; }
        public string aba { get; set; }
        public string title { get; set; }
        public string text { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
