//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Frooty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_grupo_shipping
    {
        public int id_group { get; set; }
        public int id_shipping { get; set; }
        public int id_state { get; set; }
    
        public virtual tb_states tb_states { get; set; }
        public virtual tb_shipping tb_shipping { get; set; }
    }
}
