//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Goodie.Time.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_rules
    {
        public int id_rules { get; set; }
        public Nullable<decimal> weight_bronze { get; set; }
        public Nullable<decimal> weight_silver { get; set; }
        public Nullable<decimal> weigth_gold { get; set; }
        public Nullable<int> id_user_manu { get; set; }
        public Nullable<System.DateTime> ts_user_manu { get; set; }
        public string fl_active { get; set; }
    }
}
