//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Goodie.Time.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_status_roles
    {
        public tb_status_roles()
        {
            this.tb_roles_products = new HashSet<tb_roles_products>();
        }
    
        public int id_status { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<tb_roles_products> tb_roles_products { get; set; }
    }
}
