//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Goodie.Time.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_status_shop
    {
        public tb_status_shop()
        {
            this.tb_shop = new HashSet<tb_shop>();
        }
    
        public int id_status { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<tb_shop> tb_shop { get; set; }
    }
}
