//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Frooty.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_shop()
        {
            this.td_itens_shop = new HashSet<td_itens_shop>();
        }
    
        public int id_shop { get; set; }
        public int id_partners { get; set; }
        public int id_status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> discount_total { get; set; }
        public Nullable<decimal> shipping_price { get; set; }
        public string date_payment { get; set; }
        public string id_transaction { get; set; }
        public string status_payment { get; set; }
    
        public virtual tb_partners tb_partners { get; set; }
        public virtual tb_status_shop tb_status_shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<td_itens_shop> td_itens_shop { get; set; }
    }
}
