//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Frooty.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public td_Products()
        {
            this.tb_roles_products = new HashSet<tb_roles_products>();
            this.td_itens_shop = new HashSet<td_itens_shop>();
        }
    
        public int id_products { get; set; }
        public string name { get; set; }
        public string flavour { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> price { get; set; }
        public int id_status { get; set; }
        public string picture { get; set; }
        public string description { get; set; }
        public Nullable<int> id_user_cadm { get; set; }
        public Nullable<System.DateTime> ts_user_cadm { get; set; }
        public Nullable<int> id_user_manu { get; set; }
        public Nullable<System.DateTime> ts_user_manu { get; set; }
        public string fl_active { get; set; }
        public Nullable<int> id_brands { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_roles_products> tb_roles_products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<td_itens_shop> td_itens_shop { get; set; }
        public virtual td_brands td_brands { get; set; }
    }
}
