//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Goodie.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class frootyacai_siteEntities : DbContext
    {
        public frootyacai_siteEntities()
            : base("name=frootyacai_siteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_about> tb_about { get; set; }
        public virtual DbSet<tb_business> tb_business { get; set; }
        public virtual DbSet<tb_country> tb_country { get; set; }
        public virtual DbSet<tb_events> tb_events { get; set; }
        public virtual DbSet<tb_grupo_shipping> tb_grupo_shipping { get; set; }
        public virtual DbSet<tb_launcher> tb_launcher { get; set; }
        public virtual DbSet<tb_location> tb_location { get; set; }
        public virtual DbSet<tb_login> tb_login { get; set; }
        public virtual DbSet<tb_newPost> tb_newPost { get; set; }
        public virtual DbSet<tb_partners> tb_partners { get; set; }
        public virtual DbSet<tb_recipes> tb_recipes { get; set; }
        public virtual DbSet<tb_roles_products> tb_roles_products { get; set; }
        public virtual DbSet<tb_rules> tb_rules { get; set; }
        public virtual DbSet<tb_shipping> tb_shipping { get; set; }
        public virtual DbSet<tb_shop> tb_shop { get; set; }
        public virtual DbSet<tb_states> tb_states { get; set; }
        public virtual DbSet<tb_status> tb_status { get; set; }
        public virtual DbSet<tb_status_products> tb_status_products { get; set; }
        public virtual DbSet<tb_status_roles> tb_status_roles { get; set; }
        public virtual DbSet<tb_status_shop> tb_status_shop { get; set; }
        public virtual DbSet<tb_statusPartners> tb_statusPartners { get; set; }
        public virtual DbSet<tb_typeUser> tb_typeUser { get; set; }
        public virtual DbSet<td_itens_shop> td_itens_shop { get; set; }
        public virtual DbSet<td_Products> td_Products { get; set; }
        public virtual DbSet<td_brands> td_brands { get; set; }
        public virtual DbSet<tb_about_goodie_time> tb_about_goodie_time { get; set; }
    }
}
