//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Goodie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_shipping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_shipping()
        {
            this.tb_grupo_shipping = new HashSet<tb_grupo_shipping>();
        }
    
        public int id_shipping { get; set; }
        public string ds_group { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> bronze_price { get; set; }
        public Nullable<decimal> silver_price { get; set; }
        public Nullable<decimal> gold_price { get; set; }
        public string fl_shipping { get; set; }
        public Nullable<int> id_user_cadm { get; set; }
        public Nullable<System.DateTime> ts_user_cadm { get; set; }
        public Nullable<int> id_user_manu { get; set; }
        public Nullable<System.DateTime> ts_user_manu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_grupo_shipping> tb_grupo_shipping { get; set; }
    }
}
